stat-server.apiKey=
server.port=8081
path-to-driver=
logs.path=
SAVE_TO_JSON_DIRECTORIES=./tmp
SAVE_TO_EXCEL_DIRECTORIES=./tmp
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
USER_AGENTS=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.3
spring.application.name=scraper
logging.config=file:logback-spring.xml

spring.rabbitmq.listener.simple.shutdown-timeout=3700000
spring.rabbitmq.listener.simple.receive-timeout=3700000
spring.rabbitmq.listener.simple.consumer-start-timeout=300000
spring.rabbitmq.listener.simple.delivery-timeout=3700000
spring.rabbitmq.listener.simple.retry.max-attempts=0
spring.rabbitmq.listener.simple.prefetch=1
queue-appender-enabled=true

