stat-server.apiKey=
server.port=8081
path-to-driver=
logs.path=
SAVE_TO_JSON_DIRECTORIES=./tmp
SAVE_TO_EXCEL_DIRECTORIES=./tmp
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
USER_AGENTS=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15
spring.application.name=scraper
logging.config=file:logback-spring.xml
config.read.and.apply=true
queue-appender-enabled=true

