stat-server.apiKey=
server.port=8081
path-to-driver=
logs.path=
SAVE_TO_JSON_DIRECTORIES=./tmp
SAVE_TO_EXCEL_DIRECTORIES=./tmp
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
USER_AGENTS=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.3

